"""怪物分类数据：用户提供的 BOSS/精英/普通名单。"""
from __future__ import annotations

# 格式: { "规范化名字": "Boss" | "Elite" | "Normal" }
# 名字来自游戏内显示名，用于匹配 config 文件
# TID 空的在运行时会尝试自动匹配或留 TODO

CLASSIFICATION: dict[str, str] = {

    # ═══════════ 首领 BOSS ═══════════

    "@SparxiConOfficial": "Boss",
    "Abundant Ebon Deer": "Boss",
    "Alloy Mechatron King PomPom": "Boss",
    "Annihilator of Desolation Mistral": "Boss",
    "Argenti": "Boss",
    "Blaznana Monkey Trick": "Boss",
    "Borisin Warhead Hoolay": "Boss",
    "Bronya": "Boss",
    "Cirrus": "Boss",
    "Cloud Knight Lieutenant Yanqing": "Boss",
    "Cocolia": "Boss",
    "Daring Diceroller": "Boss",
    "First Genius Entelechy Zandar": "Boss",
    "Flame Reaver of Doomsday Led Astray": "Boss",
    "Flame Reaver of the Deepest Dark": "Boss",
    "Fulminating Wolflord": "Boss",
    "Gepard": "Boss",
    "Guide of Withering and Decay": "Boss",
    "Harbinger of Death Swarm Nightmare": "Boss",
    "Ichor Memosprite Judge of Oblivion": "Boss",
    "Kafka": "Boss",
    "Live Stream Assistant": "Boss",
    "Memory Zone Meme Something Unto Death": "Boss",
    "Monitoring Automaton Prototype 2": "Boss",
    "Paramount Bliss Inverted Illwish Archlotus": "Boss",
    "Pollux Netherwing Husk Ferry of Souls": "Boss",
    "Sam": "Boss",
    "Savage God Mad King Incarnation of Strife": "Boss",
    "Silver Knight of Virtuous Gallantry": "Boss",
    "Soulhook Sovereign": "Boss",
    "Stellaron Hunter Kafka": "Boss",
    "Stellaron Hunter Sam": "Boss",
    "Super Idol Center of Attention": "Boss",
    "Svarog": "Boss",
    "Swarm True Sting": "Boss",
    "Ten Stonehearts Aventurine of Stratagems": "Boss",
    "The Giver Master of Legions Lance of Fury": "Boss",
    "The Past Present and Eternal Show": "Boss",
    "The Ravaged Unconquerable": "Boss",
    "Vessel of the Destruction Khaslana": "Boss",
    "Wonder Forest Banacademic Office Staff": "Boss",

    # ═══════════ 精英 ═══════════

    "Antimatter Engine": "Elite",
    "Aurumaton Gatekeeper": "Elite",
    "Aurumaton Spectral Envoy": "Elite",
    "Automaton Direwolf": "Elite",
    "Automaton Grizzly": "Elite",
    "Banacademic Office Charmony BananAdvisor": "Elite",
    "Black Tide Champion": "Elite",
    "Black Tide Corroded Daemon": "Elite",
    "Blaze Out of Space": "Elite",
    "Canvas Peacock": "Elite",
    "Corrupting Shadowfiend Torrential Rotbringer": "Elite",
    "Cyclonic Swarm Mother": "Elite",
    "Dark Sun Gryphon": "Elite",
    "Daybreak Squadron": "Elite",
    "Decaying Shadow": "Elite",
    "Disciples of Sanctus Medicus Shape Shifter": "Elite",
    "Dreamjolt Troupe Beyond Overcooked": "Elite",
    "Dreamjolt Troupe Sweet Gorilla": "Elite",
    "Earthshaker Leo Solblaze Winged Beast": "Elite",
    "Ecliptic Inner Beast": "Elite",
    "Elegy Siren Insatiable Leviathan": "Elite",
    "Frigid Prowler": "Elite",
    "Furiae Praetor": "Elite",
    "Greatsword Guardian Vanguard Wallbreaker": "Elite",
    "Guardian Shadow": "Elite",
    "Herta ErrorModel": "Elite",
    "Howling Casket": "Elite",
    "Ice Out of Space": "Elite",
    "Ichor Memosprite Winged Serpent": "Elite",
    "Joy Ascendant": "Elite",
    "Lady of Crashing Waves": "Elite",
    "Memory Zone Meme Shell of Faded Rage": "Elite",
    "Moonlit Pegasus": "Elite",
    "Noontide Gryphon": "Elite",
    "Rocking Rebel": "Elite",
    "Sanerot Hearteater": "Elite",
    "Searing Prowler": "Elite",
    "Senior Staff Team Leader": "Elite",
    "Silvermane Lieutenant": "Elite",
    "Stormbringer": "Elite",
    "Synergy Duo": "Elite",
    "The Ascended": "Elite",
    "Voidranger Trampler": "Elite",

    # ═══════════ 普通 ═══════════

    "All or Nothing": "Normal",
    "All or Nothing Double Fortune": "Normal",
    "Alloy Pommy": "Normal",
    "Speartip": "Normal",
    "Spirithief Bartholos": "Normal",
    "The Honored": "Normal",
    "The Shield": "Normal",
    "Abundance Lotus": "Normal",
    "Abundance Sprite Golden Hound": "Normal",
    "Abundance Sprite Wooden Lupus": "Normal",
    "Aggressive Reading Material": "Normal",
    "Antibaryon": "Normal",
    "Assistant Graffiti Demander": "Normal",
    "Assistant Graffiti Rusher": "Normal",
    "Assistant Graffiti Slacker": "Normal",
    "Automaton Beetle": "Normal",
    "Automaton Hound": "Normal",
    "Automaton Spider": "Normal",
    "Autonomous Wand": "Normal",
    "Auxiliary Robot Arm Unit": "Normal",
    "Banacademic Office Assistanana": "Normal",
    "Banacademic Office Dreamweaver BananAdvisor": "Normal",
    "Banacademic Office Fortune BananAdvisor": "Normal",
    "Baryon": "Normal",
    "Black Tide Council": "Normal",
    "Black Tide Corroded Axe": "Normal",
    "Black Tide Decrepit Bow": "Normal",
    "Cloud Knights Patroller": "Normal",
    "Conquer or Be Conquered": "Normal",
    "Dawn Left Hand": "Normal",
    "Daythunder Raven": "Normal",
    "Destruction Lotus": "Normal",
    "Disaster Right Hand": "Normal",
    "Disciples of Sanctus Medicus Ballistarius": "Normal",
    "Disciples of Sanctus Medicus Internal Alchemist": "Normal",
    "Dreamjolt Troupe Birdskull": "Normal",
    "Dreamjolt Troupe Bubble Hound": "Normal",
    "Dreamjolt Troupe Fortune Seller": "Normal",
    "Dreamjolt Troupe Mr Domescreen": "Normal",
    "Dreamjolt Troupe Spring Loader": "Normal",
    "Dreamjolt Troupe Winder Goon": "Normal",
    "Dried Lacrimal Bone": "Normal",
    "Echo of Faded Dreams": "Normal",
    "Eclipse Wolftrooper": "Normal",
    "Entranced Ingenium Golden Cloud Toad": "Normal",
    "Entranced Ingenium Illumination Dragonfish": "Normal",
    "Entranced Ingenium Obedient Dracolion": "Normal",
    "Everwinter Shadewalker": "Normal",
    "Flamespawn": "Normal",
    "Flying Sword": "Normal",
    "Frostspawn": "Normal",
    "Furbo Journalist": "Normal",
    "Furiae Archer": "Normal",
    "Furiae Philosopher": "Normal",
    "Furiae Troupe": "Normal",
    "Furiae Warrior": "Normal",
    "Gnaw Sting": "Normal",
    "Grunt Field Personnel": "Normal",
    "Grunt Security Personnel": "Normal",
    "Hallucinogenic Mermaid": "Normal",
    "Ice Edge": "Normal",
    "Ichor Memosprite Canine": "Normal",
    "Ichor Memosprite Pheasant": "Normal",
    "Illwish Lotus": "Normal",
    "Imaginary Weaver": "Normal",
    "Imprisoned Mythos": "Normal",
    "Incineration Shadewalker": "Normal",
    "Juvenile Sting": "Normal",
    "Lance of the Eternal Freeze": "Normal",
    "Languid Ethmoid Bone": "Normal",
    "Lesser Sting": "Normal",
    "Long-Shattered Vessel": "Normal",
    "Lordly Trashcan": "Normal",
    "Magical Girl Troupe": "Normal",
    "Manipulated Logos": "Normal",
    "Mara-Struck Soldier": "Normal",
    "Mara-Struck Warden": "Normal",
    "Mask of No Thought": "Normal",
    "Memory Zone Meme Allseer": "Normal",
    "Memory Zone Meme Heartbreaker": "Normal",
    "Memory Zone Meme Insatiable Vanity": "Normal",
    "Memory Zone Meme Something In The Mirror": "Normal",
    "Meteoric Eagle": "Normal",
    "Mirage Fizzle Kid": "Normal",
    "Nebula Devourer": "Normal",
    "Output Port 1": "Normal",
    "Output Port 2": "Normal",
    "Planeshred Claws": "Normal",
    "SD Civilian Mechatron": "Normal",
    "Sableclaw Wolftrooper": "Normal",
    "Security Doggo": "Normal",
    "Sequence Trotter": "Normal",
    "Servant of Tides": "Normal",
    "Shadow Jackhyena": "Normal",
    "Shadow of Hatred": "Normal",
    "Shoot of Hundred Eyes": "Normal",
    "Silvermane Cannoneer": "Normal",
    "Silvermane Gunner": "Normal",
    "Silvermane Soldier": "Normal",
    "Sombrous Sepulcher": "Normal",
    "Ternary Assimilation Unit": "Normal",
    "The Conquered": "Normal",
    "The Long Arms of Sorrow": "Normal",
    "Thunderspawn": "Normal",
    "Tide-Eroded Blade": "Normal",
    "Trot Deuce": "Normal",
    "Trot Prime": "Normal",
    "Trot Tri": "Normal",
    "Trotter of Abundance": "Normal",
    "Trotter of Destruction": "Normal",
    "Trotter of Preservation": "Normal",
    "Twig of Glorious Blooms": "Normal",
    "Twig of Hundred Eyes": "Normal",
    "Twig of Lavish Fruits": "Normal",
    "Twig of Marple Leaf": "Normal",
    "Twig of Wintry Wind": "Normal",
    "Vagrant": "Normal",
    "Voidranger Distorter": "Normal",
    "Voidranger Eliminator": "Normal",
    "Voidranger Reaver": "Normal",
    "Warp Trotter": "Normal",
    "Windspawn": "Normal",
    "Worldpurge Tail": "Normal",
    "Wraith Warden": "Normal",
}
